Root Cause Analysis:  Resolution
Summary:  Name
Description:  Description
Created By:  CreatedBy.Name
Release:  Parent.Name
-Custom_JIRAIntStatus.Name:  Custom_JIRAIntStatus.Name
VersionAffected:  VersionAffected
VersionAffected:  Custom_CAPVersionAffected2.Name
Created Date/Time:  CreateDate
Components:  Custom_CAPComponent.Name
Environment:  Environment
Release Milestone:  Custom_CAPReleaseMilestone.Name

